"""Embed the standalone editor page in ESP32 program flash."""
from pathlib import Path

folder = Path(__file__).resolve().parent
html = (folder / 'editor.html').read_text()
assert ')POV_HTML"' not in html
(folder / 'web_assets.h').write_text(
    '// Generated by embed_web.py from editor.html.\n'
    '#pragma once\n#include <Arduino.h>\n'
    'static const char editorHtml[] PROGMEM = R"POV_HTML(' + html + ')POV_HTML";\n'
)
